---
- hosts: all
  connection: ssh
  gather_facts: no
  tasks:
    - name: Capture all vars on remote host
      set_fact:
        all_vars: "{{ hostvars[inventory_hostname] }}"
    - name: Print hostname
      command: hostname
    # - name: Print vars to file on remote host
    #   copy:
    #     content: "{{ all_vars | to_nice_yaml }}"
    #     dest: "/tmp/printed_vars_step_3.yml"
    # - name: Write hostname to file
    #   copy:
    #     content: "{{ ansible_hostname }}"
    #     dest: "/tmp/current_hostname_play.txt"
    - name: Save test message to a file
      copy:
        content: "{{ message }}"
        dest: "/tmp/{{ filename }}.txt"
