---
- hosts: localhost
  connection: local
  tasks:
    - name: Capture all vars
      set_fact:
        all_vars: "{{ hostvars[inventory_hostname] }}"
    - name: Print all vars
      debug:
        var: all_vars
    - name: Write all vars to file
      copy:
        content: "{{ all_vars | to_nice_yaml }}"
        dest: "/tmp/printed_vars.yml"
    - ansible.builtin.add_host:
        name: "{{ fqdn }}"
        groups: group1

- hosts: group1
  remote_user: root
  gather_facts: yes
  vars:
    ansible_user: "{{ vm_root_user }}"
    ansible_ssh_pass: "{{ vm_root_password }}"
  tasks:
    - name: Save message to a file
      copy:
        content: "{{ message }}"
        dest: "/tmp/test.txt"
